mongo-url = "mongodb://root:root@mongo.demo.network:27017"
elasticsearch-urls = ["http://elasticsearch:9200"]
direct-read-namespaces = ["domain.users", "domain.items"]
change-stream-namespaces = ["domain.users", "domain.items"]
verbose = true

[[mapping]]
namespace = "domain.users"
index = "domain_users"
type = "_doc"

[[mapping]]
namespace = "domain.items"
index = "domain_items_v1_0_1"
type = "_doc"
