version: "3.7"
services:
  monstache:
    build: 
      context: .
    environment:
      - ES_USERS_INDEX=domain_users
    volumes:
      - ./:/app
    command: sh -c '/app/scripts/wait-for.sh mongo.demo.network:27017 elasticsearch:9200 -- monstache -f /app/config.toml'

  
  #mongo:
  #  image: mongo:4.0
  #  ports: 
  #    - 27017:27017
  #  volumes:
  #    - ./scripts:/scripts
  #    - mongo:/data/db
  #  environment:
  #    - MONGODB_ADDRESSES=mongo:27017
  #    - MONGODB_DATABASE=domain
  #    - MONGODB_USERNAME=user
  #    - MONGODB_PASSWORD=password
  #    - MONGODB_REPLICATE_SET=rs
  #  entrypoint: ["scripts/mongo-setup.sh"]

  elasticsearch:
    image: elasticsearch:6.8.5
    ports: 
      - 9200:9200

  kibana:
    image: kibana:6.8.5
    ports: 
      - 5601:5601

#volumes:
#  mongo:

networks:
  default:
    external:
      name: demo.network
